# Generated by Django 4.2.16 on 2026-04-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='id_nodo_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_inicio', to='nodos.nodo'),
        ),
    ]
