# Generated by Django 4.2.16 on 2026-04-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        ('nodos', '0001_initial'),
        ('historias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('izquierda', 'Izquierda'), ('centro', 'Centro'), ('derecha', 'Derecha')], default='centro', max_length=10)),
                ('id_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_personajes', to='nodos.nodo')),
            ],
            options={
                'verbose_name': 'Nodo Personaje',
                'verbose_name_plural': 'Nodo Personajes',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='historias.historia')),
                ('id_imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='recursos.imagen')),
                ('nodos', models.ManyToManyField(related_name='personajes', through='personajes.NodoPersonaje', to='nodos.nodo')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
        migrations.AddField(
            model_name='nodopersonaje',
            name='id_personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_personajes', to='personajes.personaje'),
        ),
        migrations.AlterUniqueTogether(
            name='nodopersonaje',
            unique_together={('id_nodo', 'id_personaje')},
        ),
    ]
