sonar.projectKey=sonar-prueba-d
sonar.projectName=sonar-prueba-d
sonar.projectVersion=1.0

# Codigo fuente Frontend del proyecto
# Ajustado a la estructura actual del repositorio
# carpeta principal Frontend: front
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Analizar solo archivos JavaScript/TypeScript
sonar.inclusions=**/*.{js,jsx,ts,tsx}

# Excluir artefactos no relevantes
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.venv/**,**/env/**,**/venv/**

# Tests
# sonar.tests=apps
# sonar.test.inclusions=**/tests/**/.py,**/test_.py