# Generated by Django 4.2.16 on 2026-04-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nodo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('es_final', models.BooleanField(default=False)),
                ('id_audio_fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_con_audio', to='recursos.audio')),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='historias.historia')),
                ('id_imagen_escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos_como_escenario', to='recursos.imagen')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=300)),
                ('id_nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_destino', to='nodos.nodo')),
                ('id_nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_origen', to='nodos.nodo')),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
            },
        ),
    ]
